# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oola9SmroT9eZioJaFrZbhG_wUzOWTcH
"""

# Task 03
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score
import matplotlib.pyplot as plt

df = pd.read_csv("bank_marketing_task03_data.csv")

X = df.drop(columns="y")
y = (df["y"] == "yes").astype(int)

categorical = X.select_dtypes(include="object").columns
numeric = X.select_dtypes(exclude="object").columns

preprocessor = ColumnTransformer([
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical),
    ("num", "passthrough", numeric)
])

model = DecisionTreeClassifier(
    criterion="entropy",
    max_depth=5,
    min_samples_leaf=30,
    class_weight="balanced",
    random_state=42
)

pipe = Pipeline([
    ("preprocessor", preprocessor),
    ("model", model)
])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, stratify=y, random_state=42
)

pipe.fit(X_train, y_train)

pred = pipe.predict(X_test)
prob = pipe.predict_proba(X_test)[:, 1]

print("Accuracy :", accuracy_score(y_test, pred))
print("Precision:", precision_score(y_test, pred))
print("Recall   :", recall_score(y_test, pred))
print("F1-score :", f1_score(y_test, pred))
print("ROC-AUC  :", roc_auc_score(y_test, prob))
print("Confusion matrix:\n", confusion_matrix(y_test, pred))

features = pipe.named_steps["preprocessor"].get_feature_names_out()
tree = pipe.named_steps["model"]

plt.figure(figsize=(24, 12))
plot_tree(
    tree,
    feature_names=features,
    class_names=["No purchase", "Purchase"],
    filled=True,
    rounded=True,
    max_depth=3,
    fontsize=8
)
plt.tight_layout()
plt.show()